stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Criando aplicação..."

test_job:
  stage: test
  script:
    - echo "Rodando testes..."

deploy_job:
  stage: deploy
  script:
    - echo "Enviando aplicação..."
